"""Fluent builder for CROPro pipeline configuration.

``PipelineConfig`` is the easiest way to define a full CROPro pipeline in
pure Python.  It covers the same settings as a TOML schema file — dataset
paths, naming suffixes, crop options, split ratios, pipeline flags, and
clinical metadata — but lets you set them with typed methods and IDE
autocomplete instead of editing a text file.

The class bridges two config formats that CROPro understands:

* **TOML schema file** (e.g. ``config/my_dataset.toml``) — the complete
  dataset definition read by every pipeline via ``--schema``.  Recommended
  when you want a reusable, shareable config that can be checked into source
  control.  ``PipelineConfig.save()`` writes this format.

* **INI file** (e.g. ``config/resample_paths.ini``) — a lightweight,
  paths-only shortcut for the *resample* pipeline only, consumed by
  ``cropro resample --config``.  Useful for quick one-off resampling jobs
  where you only want to override the folder paths and nothing else.  For
  anything more than path overrides, use a TOML schema instead.

Quick example::

    from cropro import PipelineConfig

    cfg = (
        PipelineConfig("MyDataset")
        .paths(
            images_root="dataset/MyDataset/images",
            output_root="dataset/MyDataset/images_resampled",
            cropro_root="dataset/MyDataset/cropped_images",
            gland_root="dataset/MyDataset/masks/gland",
            lesion_root="none",       # "none" disables the mask step
            archives_root="none",
        )
        .naming(
            t2w_suffix="_t2w.mha",
            adc_suffix="_adc.mha",
            hbv_suffix="_hbv.mha",
            mask_suffix=".nii.gz",
        )
        .crop(
            sequence_type="bpMRI",
            pixel_spacing=0.4,
            crop_image_size=128,
            crop_method="random",
            do_normalization=True,
            saved_image_type="png",
        )
        .normalization(
            t2w="autoref",
            adc="percentile",
            hbv="percentile",
            t2w_min_percentile=0.5,
            t2w_max_percentile=99.5,
            adc_min_percentile=0.5,
            adc_max_percentile=99.5,
            hbv_min_percentile=0.5,
            hbv_max_percentile=99.9,
        )
        .split(train_ratio=0.70, val_ratio=0.15, test_ratio=0.15, seed=42)
        .pipeline(resample_dataset=True, normalize_before_resample=True)
    )

    # Save as a TOML schema (re-usable with --schema on any pipeline)
    cfg.save("config/my_dataset.toml")

    # Convert to DatasetSchema for use in Python code
    schema = cfg.to_schema()

Load and override an existing schema::

    cfg = PipelineConfig.load("config/my_dataset.toml")
    cfg.crop(pixel_spacing=0.5, crop_method="stride")
    cfg.save("config/my_dataset_stride_0.5mm.toml")
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from cropro.schema import DatasetSchema

# ---------------------------------------------------------------------------
# Internal TOML writer (no third-party deps required)
# ---------------------------------------------------------------------------

def _toml_value(v: Any) -> str:
    """Serialise a Python value to an inline TOML literal."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        escaped = v.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(v, list):
        items = ", ".join(_toml_value(i) for i in v)
        return f"[{items}]"
    return str(v)


def _render_toml(dataset_name: str, sections: dict[str, dict[str, Any]]) -> str:
    lines: list[str] = [
        "# CROPro pipeline schema",
        f'# Generated by PipelineConfig("{dataset_name}")',
        "#",
        "# Use with:  cropro resample --schema <this file>",
        "#            cropro crop     --schema <this file>",
        "#            cropro normalize --schema <this file>",
        "#",
        "# CLI flags always override schema values.",
        "",
        "[dataset]",
        f'name = "{dataset_name}"',
    ]
    for section, data in sections.items():
        if not data:
            continue
        lines.append("")
        lines.append(f"[{section}]")
        for key, value in data.items():
            lines.append(f"{key} = {_toml_value(value)}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public class
# ---------------------------------------------------------------------------

class PipelineConfig:
    """Fluent builder for a CROPro dataset + pipeline configuration.

    Each method returns ``self`` so calls can be chained.  Call
    :meth:`save` to write the config as a TOML schema file, or
    :meth:`to_schema` to get a :class:`~cropro.schema.DatasetSchema`
    for use in Python.

    Parameters
    ----------
    dataset_name:
        Human-readable name embedded in the TOML ``[dataset]`` section.
        Used to derive the crop output folder name when ``cropro_root`` is
        set (e.g. ``MyDataset_random_0.4_128``).
    """

    def __init__(self, dataset_name: str = "MyDataset") -> None:
        self._name = dataset_name
        self._paths: dict[str, Any] = {}
        self._naming: dict[str, Any] = {}
        self._crop: dict[str, Any] = {}
        self._split: dict[str, Any] = {}
        self._pipeline: dict[str, Any] = {}
        self._metadata: dict[str, Any] = {}

    # ------------------------------------------------------------------
    # Chainable setters
    # ------------------------------------------------------------------

    def paths(
        self,
        *,
        images_root: str | None = None,
        output_root: str | None = None,
        archives_root: str | None = None,
        gland_root: str | None = None,
        lesion_root: str | None = None,
        cropro_root: str | None = None,
        normalized_t2w_root: str | None = None,
    ) -> PipelineConfig:
        """Set dataset folder paths.

        Parameters
        ----------
        images_root:
            Directory that contains the raw image cases.  The resample
            pipeline searches this recursively for T2W files.
        output_root:
            Destination for resampled (T2W-aligned) copies.
        archives_root:
            Directory of ``*.zip`` image archives.  The resample pipeline
            unpacks them into *images_root* before aligning.  Pass
            ``"none"`` to disable.  Leave unset to use
            ``<images_root>/../archives``.
        gland_root:
            Directory of whole-gland segmentation masks.  Pass ``"none"``
            to skip.
        lesion_root:
            Directory of lesion segmentation masks.  Pass ``"none"`` to
            skip.
        cropro_root:
            Base folder for all CROPro crop outputs.  Each run writes to
            ``<cropro_root>/<Name>_<method>_<spacing>_<size>/``.
        normalized_t2w_root:
            Destination for pre-normalised T2W volumes written before
            resampling.  Defaults to
            ``<images_root>/../normalized/<method>_t2w``.
        """
        for key, val in {
            "images_root": images_root,
            "output_root": output_root,
            "archives_root": archives_root,
            "gland_root": gland_root,
            "lesion_root": lesion_root,
            "cropro_root": cropro_root,
            "normalized_t2w_root": normalized_t2w_root,
        }.items():
            if val is not None:
                self._paths[key] = val
        return self

    def naming(
        self,
        *,
        t2w_suffix: str | None = None,
        adc_suffix: str | None = None,
        hbv_suffix: str | None = None,
        mask_suffix: str | None = None,
    ) -> PipelineConfig:
        """Set filename suffixes used to discover image and mask files.

        Parameters
        ----------
        t2w_suffix:
            Suffix that identifies T2W files (e.g. ``"_t2w.mha"``).
        adc_suffix:
            Suffix that identifies ADC files (e.g. ``"_adc.mha"``).
        hbv_suffix:
            Suffix that identifies HBV/DWI files (e.g. ``"_hbv.mha"``).
        mask_suffix:
            Suffix shared by gland and lesion masks (e.g. ``".nii.gz"``).
        """
        for key, val in {
            "t2w_suffix": t2w_suffix,
            "adc_suffix": adc_suffix,
            "hbv_suffix": hbv_suffix,
            "mask_suffix": mask_suffix,
        }.items():
            if val is not None:
                self._naming[key] = val
        return self

    def crop(
        self,
        *,
        sequence_type: str | None = None,
        pixel_spacing: float | None = None,
        crop_image_size: int | None = None,
        crop_stride: int | None = None,
        crop_method: str | None = None,
        sample_number: int | None = None,
        saved_image_type: str | None = None,
        do_normalization: bool | None = None,
        c_min_positive: float | None = None,
        c_min_negative: float | None = None,
        keep_all_slice: bool | None = None,
        skip_existing_slices: bool | None = None,
        number_of_slices_to_exclude_from_mask_gland: int | None = None,
        tumor_label_level: int | None = None,
        random_seed: int | None = None,
    ) -> PipelineConfig:
        """Set crop parameters.

        Parameters
        ----------
        sequence_type:
            ``"T2W"`` for T2W-only crops or ``"bpMRI"`` to crop T2W,
            ADC and HBV together.
        pixel_spacing:
            Target in-plane resolution in mm/pixel before cropping
            (e.g. ``0.4``).
        crop_image_size:
            Output crop width and height in pixels (e.g. ``128``).
        crop_stride:
            Grid step in pixels when ``crop_method="stride"``
            (e.g. ``32``).
        crop_method:
            ``"center"``, ``"random"``, or ``"stride"``.  Use ``"random"``
            for training and ``"stride"`` for validation / test to ensure
            full prostate coverage.
        sample_number:
            Number of random crops per slice when ``crop_method="random"``.
        saved_image_type:
            Output file format: ``"png"``, ``"tiff"``, ``"npy"``, etc.
        do_normalization:
            Normalise crop intensities before saving.  When ``True``, each
            modality uses the strategy set via :meth:`normalization`.
        c_min_positive:
            Minimum lesion-overlap fraction to keep a positive crop.
        c_min_negative:
            Minimum gland coverage for negative crop selection.
        keep_all_slice:
            ``True`` to include every gland slice (required for
            patient-level inference).
        skip_existing_slices:
            Skip writing slices whose output files already exist (safe for
            resuming interrupted runs).
        number_of_slices_to_exclude_from_mask_gland:
            Number of edge slices to drop from the gland region.
        tumor_label_level:
            Label value treated as lesion tissue in the lesion mask.
        random_seed:
            Optional integer seed for reproducible random sampling.
        """
        for key, val in {
            "sequence_type": sequence_type,
            "pixel_spacing": pixel_spacing,
            "crop_image_size": crop_image_size,
            "crop_stride": crop_stride,
            "crop_method": crop_method,
            "sample_number": sample_number,
            "saved_image_type": saved_image_type,
            "do_normalization": do_normalization,
            "c_min_positive": c_min_positive,
            "c_min_negative": c_min_negative,
            "keep_all_slice": keep_all_slice,
            "skip_existing_slices": skip_existing_slices,
            "number_of_slices_to_exclude_from_mask_gland": number_of_slices_to_exclude_from_mask_gland,
            "tumor_label_level": tumor_label_level,
            "random_seed": random_seed,
        }.items():
            if val is not None:
                self._crop[key] = val
        return self

    def normalization(
        self,
        *,
        t2w: str | None = None,
        adc: str | None = None,
        hbv: str | None = None,
        t2w_min_percentile: float | None = None,
        t2w_max_percentile: float | None = None,
        adc_min_percentile: float | None = None,
        adc_max_percentile: float | None = None,
        hbv_min_percentile: float | None = None,
        hbv_max_percentile: float | None = None,
        vmax_number: int | None = None,
    ) -> PipelineConfig:
        """Set per-modality normalization strategies and percentile windows.

        This is a convenience shortcut: the values are stored in the
        ``[crop]`` section, matching how the TOML schema and
        :class:`~cropro.config.CropConfig` work.

        Parameters
        ----------
        t2w:
            Normalization strategy for T2W: ``"autoref"``, ``"percentile"``,
            ``"gaussian"``, or ``"zscore_clip"``.  Defaults to
            ``"autoref"``.
        adc:
            Normalization strategy for ADC.  ``"autoref"`` is not valid
            here; defaults to ``"percentile"``.
        hbv:
            Normalization strategy for HBV.  ``"autoref"`` is not valid
            here; defaults to ``"percentile"``.
        t2w_min_percentile / t2w_max_percentile:
            Intensity window for T2W clipping/display.
        adc_min_percentile / adc_max_percentile:
            Intensity window for ADC clipping/display.
        hbv_min_percentile / hbv_max_percentile:
            Intensity window for HBV clipping/display.
        vmax_number:
            Maximum display value used in the legacy normalised-image path.
        """
        mapping = {
            "t2w_normalization_method": t2w,
            "adc_normalization_method": adc,
            "hbv_normalization_method": hbv,
            "t2w_min_percentile": t2w_min_percentile,
            "t2w_max_percentile": t2w_max_percentile,
            "adc_min_percentile": adc_min_percentile,
            "adc_max_percentile": adc_max_percentile,
            "hbv_min_percentile": hbv_min_percentile,
            "hbv_max_percentile": hbv_max_percentile,
            "normalized_vmaxNumber": vmax_number,
        }
        for key, val in mapping.items():
            if val is not None:
                self._crop[key] = val
        return self

    def split(
        self,
        *,
        enabled: bool | None = None,
        train_ratio: float | None = None,
        val_ratio: float | None = None,
        test_ratio: float | None = None,
        seed: int | None = None,
        stratify: bool | None = None,
        split_level: str | None = None,
        human_labels_root: str | None = None,
    ) -> PipelineConfig:
        """Configure patient-level train / val / test splitting.

        Parameters
        ----------
        enabled:
            ``True`` to split cases before cropping.  When ``False``, all
            crops are written to a single flat output folder.
        train_ratio / val_ratio / test_ratio:
            Fractions for each subset; must sum to 1.0.
        seed:
            Random seed for reproducible shuffling.
        stratify:
            Preserve the positive fraction in each subset.
        split_level:
            ``"patient"`` — all gland slices (required for patient-level
            inference); ``"lesion"`` — only lesion / central slices.
        human_labels_root:
            Directory of human-expert annotation files.  Only cases with a
            file here are eligible for the **test** set; AI-annotated
            positives are restricted to train / val.  Leave unset or pass
            ``""`` to allow all cases in the test set.
        """
        for key, val in {
            "enabled": enabled,
            "train_ratio": train_ratio,
            "val_ratio": val_ratio,
            "test_ratio": test_ratio,
            "seed": seed,
            "stratify": stratify,
            "split_level": split_level,
            "human_labels_root": human_labels_root,
        }.items():
            if val is not None:
                self._split[key] = val
        return self

    def pipeline(
        self,
        *,
        resample_dataset: bool | None = None,
        normalize_before_resample: bool | None = None,
        normalize_method: str | None = None,
        normalize_workers: int | None = None,
        already_resampled: bool | None = None,
    ) -> PipelineConfig:
        """Set high-level pipeline execution flags.

        Parameters
        ----------
        resample_dataset:
            When ``True``, one ``cropro crop --schema`` command performs
            dataset-level resampling first and then crops the output.
        normalize_before_resample:
            When ``True``, normalize every T2W volume first and use the
            normalized copies as the T2W reference during resampling.
        normalize_method:
            Normalization strategy used by *normalize_before_resample*
            (default ``"autoref"``).
        normalize_workers:
            Number of parallel threads for the normalization pre-step.
            ``None`` picks a conservative automatic value.
        already_resampled:
            Set ``True`` when *images_root* already contains resampled
            data so the resample pre-step is skipped.
        """
        for key, val in {
            "resample_dataset": resample_dataset,
            "normalize_before_resample": normalize_before_resample,
            "normalize_method": normalize_method,
            "normalize_workers": normalize_workers,
            "already_resampled": already_resampled,
        }.items():
            if val is not None:
                self._pipeline[key] = val
        return self

    def metadata(
        self,
        *,
        csv_path: str | None = None,
        case_id_columns: list[str] | None = None,
        case_id_format: str | None = None,
        positive_column: str | None = None,
        positive_values: list[str] | None = None,
        manifest_columns: list[str] | None = None,
    ) -> PipelineConfig:
        """Set clinical metadata options (optional; used for label-aware splits).

        Parameters
        ----------
        csv_path:
            Path to a CSV file with per-case clinical information.  Each
            row corresponds to one case.
        case_id_columns:
            Column names whose values are joined to build the case stem
            (e.g. ``["patient_id", "study_id"]``).
        case_id_format:
            Python format string to build the stem from *case_id_columns*
            (e.g. ``"{patient_id}_{study_id}"``).
        positive_column:
            Column whose value classifies a case as positive.
        positive_values:
            Values in *positive_column* that mean positive (e.g.
            ``["YES"]``).
        manifest_columns:
            CSV columns to embed in the split manifest (e.g.
            ``["case_csPCa", "case_ISUP"]``).
        """
        for key, val in {
            "csv_path": csv_path,
            "case_id_columns": case_id_columns,
            "case_id_format": case_id_format,
            "positive_column": positive_column,
            "positive_values": positive_values,
            "manifest_columns": manifest_columns,
        }.items():
            if val is not None:
                self._metadata[key] = val
        return self

    # ------------------------------------------------------------------
    # I/O
    # ------------------------------------------------------------------

    @classmethod
    def load(cls, path: str | Path) -> PipelineConfig:
        """Load from an existing TOML schema file.

        Returns a :class:`PipelineConfig` pre-populated with the values
        from that file.  You can then call any setter to override
        individual settings before saving or using the config.

        Parameters
        ----------
        path:
            Path to a ``.toml`` schema file (e.g.
            ``config/my_dataset.toml``).
        """
        schema = DatasetSchema.load(path)
        obj = cls(dataset_name=schema.name or "MyDataset")
        obj._paths = dict(schema.paths)
        obj._naming = dict(schema.naming)
        obj._crop = dict(schema.crop)
        obj._split = dict(schema.split)
        obj._pipeline = dict(schema.pipeline)
        obj._metadata = dict(schema.metadata)
        return obj

    def save(self, path: str | Path) -> Path:
        """Write the configuration as a TOML schema file.

        The output file can be passed to any CROPro pipeline via
        ``--schema``.  CLI flags always override values in the file.

        Parameters
        ----------
        path:
            Destination ``.toml`` file path.  The parent directory is
            created automatically if it does not exist.

        Returns
        -------
        Path
            Resolved path of the written file.
        """
        dest = Path(path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        sections = {
            "paths": self._paths,
            "naming": self._naming,
            "crop": self._crop,
            "split": self._split,
            "pipeline": self._pipeline,
            "metadata": self._metadata,
        }
        dest.write_text(_render_toml(self._name, sections), encoding="utf-8")
        return dest.resolve()

    # ------------------------------------------------------------------
    # Conversion
    # ------------------------------------------------------------------

    def to_schema(self) -> DatasetSchema:
        """Return a :class:`~cropro.schema.DatasetSchema` for use in Python.

        This lets you pass the config directly to internal CROPro helpers
        that accept a ``DatasetSchema`` without writing a file first.
        """
        return DatasetSchema(
            name=self._name,
            paths=dict(self._paths),
            naming=dict(self._naming),
            crop=dict(self._crop),
            split=dict(self._split),
            pipeline=dict(self._pipeline),
            metadata=dict(self._metadata),
        )

    # ------------------------------------------------------------------
    # Repr
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        sections = []
        if self._paths:
            sections.append(f"paths={list(self._paths)}")
        if self._naming:
            sections.append(f"naming={list(self._naming)}")
        if self._crop:
            sections.append(f"crop={list(self._crop)}")
        if self._split:
            sections.append(f"split={list(self._split)}")
        if self._pipeline:
            sections.append(f"pipeline={list(self._pipeline)}")
        return f"PipelineConfig({self._name!r}, {', '.join(sections)})"
